version: "3.3"
services:
  app:
    container_name: tradeshift-container
    restart: always
    build: .
    image: tradeshift-server:1.0
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - 3000:${PORT_NUMBER}
    depends_on:
      - mongo

  mongo:
    container_name: tradeshift-mongo-container
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
